# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-09 05:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        ('truck', '__first__'),
        ('inventory', '0003_auto_20181109_0501'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MechachicTimeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('type_time', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('type_time', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PartsByTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('time_labor', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Client')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.Truck')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.WorkOrder'),
        ),
        migrations.AddField(
            model_name='partsbytask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.Task'),
        ),
        migrations.AddField(
            model_name='mechanictime',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.Task'),
        ),
        migrations.AddField(
            model_name='mechanictime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mechachictimetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.Task'),
        ),
        migrations.AddField(
            model_name='mechachictimetask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
