# Generated by Django 2.2.4 on 2020-11-12 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('truck', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(blank=True, max_length=30, null=True)),
                ('total_parts', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('total_labor', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('total_work_order', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('status', models.CharField(choices=[('quote', 'Quote'), ('dropped_off', 'Dropped Off'), ('in_process', 'In Process'), ('closed', 'Closed Work Order'), ('paid', 'Paid Work Order')], default='quotes', max_length=150)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Client')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck.Truck')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('time_labor', models.DecimalField(decimal_places=2, max_digits=100)),
                ('total_parts', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('total_labor', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('total_task', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('status', models.CharField(choices=[('no_assigned', 'No assigned'), ('in_process', 'In Process'), ('completed', 'Completed')], default='no_assigned', max_length=150)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.WorkOrder')),
            ],
        ),
        migrations.CreateModel(
            name='PartsByTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('operation', models.CharField(blank=True, max_length=10, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Part')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.Task')),
            ],
        ),
        migrations.CreateModel(
            name='MechachicTimeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('clock_in', models.BooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
