# Generated by Django 2.2.4 on 2020-12-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partsbytask',
            unique_together={('task', 'part')},
        ),
    ]
