# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-11 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_orders', '0002_auto_20181109_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechachicTimeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('type_time', models.CharField(max_length=15)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_orders.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
