# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-13 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0004_auto_20181113_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanictimeday',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mechachictimetask',
            name='type_time',
        ),
        migrations.AddField(
            model_name='mechachictimetask',
            name='clock_in',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MechanicTimeDay',
        ),
    ]
