# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-05 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0005_auto_20181113_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='number_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
