# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-05 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0006_auto_20181205_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
