# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-16 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0007_workorder_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsbytask',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
