# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-18 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0008_partsbytask_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsbytask',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
