# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-22 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0010_auto_20190121_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='total_task',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
