# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-22 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0011_task_total_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsbytask',
            name='operation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
