# Generated by Django 2.1.7 on 2019-03-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0012_partsbytask_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='total_labor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='total_parts',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='total_work_order',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
