# Generated by Django 2.1.7 on 2019-03-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0014_auto_20190322_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('in_process', 'In Process'), ('closed', 'Closed Work Order'), ('paid', 'Paid Work Order')], default='in_process', max_length=150),
        ),
    ]
