# Generated by Django 2.1.7 on 2019-03-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0016_auto_20190331_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('no_assigned', 'No assigned'), ('in_process', 'In Process'), ('completed', 'Completed')], default='no_assigned', max_length=150),
        ),
    ]
