# Generated by Django 2.2.4 on 2019-09-16 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0019_auto_20190331_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
