# Generated by Django 2.2.4 on 2020-11-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('existence', models.IntegerField()),
                ('available', models.IntegerField()),
            ],
        ),
    ]
