# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-09 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20181109_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
