# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-21 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20181109_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
